# Generated by Django 4.1.3 on 2023-06-20 09:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_alter_paper_creation_date_alter_paper_update_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoring', '0010_remove_scorepackage_scorable_and_more'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('paper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.paper')),
                ('min_grade', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)])),
                ('max_grade', models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)])),
                ('conditions', models.TextField(blank=True, null=True)),
                ('accepting_status', models.CharField(choices=[('AutoAccept', 'Autoaccept'), ('CorrectAccept', 'Correctaccept'), ('Manual', 'Manual')], default='AutoAccept', max_length=15)),
                ('gender_partition_status', models.CharField(choices=[('OnlyMale', 'Onlymale'), ('OnlyFemale', 'Onlyfemale'), ('BothPartitioned', 'Bothpartitioned'), ('BothNonPartitioned', 'Bothnonpartitioned')], default='BothPartitioned', max_length=25)),
                ('audience_type', models.CharField(choices=[('Student', 'Student'), ('Academic', 'Academic'), ('All', 'All')], default='Student', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('base.paper',),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('deliverable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoring.deliverable')),
                ('type', models.CharField(choices=[('RegistrationReceipt', 'Registrationreceipt')], max_length=25)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='my_form.form')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_registration_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'form')},
            },
            bases=('scoring.deliverable',),
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_form.form')),
                ('has_certificate', models.BooleanField(default=True)),
                ('certificates_ready', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('my_form.form',),
        ),
        migrations.CreateModel(
            name='RegistrationReceipt',
            fields=[
                ('receipt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_form.receipt')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting')], default='Waiting', max_length=25)),
                ('is_participating', models.BooleanField(default=False)),
                ('certificate', models.FileField(blank=True, default=None, null=True, upload_to='certificates/')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_members', to='group.group')),
            ],
            options={
                'abstract': False,
            },
            bases=('my_form.receipt',),
        ),
    ]
