# Generated by Django 3.0.8 on 2020-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='workshop/'),
        ),
        migrations.AddField(
            model_name='fsm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
