# Generated by Django 3.1 on 2021-08-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfileanswer',
            name='answer_file',
            field=models.FileField(max_length=4000, upload_to='answers'),
        ),
    ]
