# Generated by Django 3.0.8 on 2020-11-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fsm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_workshop', to='accounts.Player')),
                ('current_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_workshop', to='fsm.FSMState')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_workshop', to='fsm.FSM')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('answer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fsm.Answer')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submited_answers', to='accounts.Participant')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submited_answers', to='fsm.Problem')),
                ('team_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='fsm.TeamHistory')),
            ],
        ),
        migrations.DeleteModel(
            name='SubmitedAnswer',
        ),
    ]
