# Generated by Django 3.0.8 on 2021-03-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0002_auto_20210307_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maximum_participant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
