# Generated by Django 3.0.8 on 2020-08-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0002_fsmpage_init_whiteboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsmpage',
            name='init_whiteboard',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
