# Generated by Django 3.0.8 on 2020-08-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0002_auto_20200821_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget', to='fsm.FSMPage'),
        ),
    ]
