# Generated by Django 3.0.8 on 2020-11-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0002_auto_20201108_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerworkshop',
            old_name='Player',
            new_name='player',
        ),
    ]
