# Generated by Django 3.1 on 2021-08-17 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0002_auto_20210817_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biganswer',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='fsm.biganswerproblem'),
        ),
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='fsm.multichoiceproblem'),
        ),
        migrations.AlterField(
            model_name='uploadfileanswer',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='fsm.uploadfileproblem'),
        ),
    ]
