# Generated by Django 3.1 on 2020-08-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0002_fsmedge_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.widget')),
                ('name', models.CharField(max_length=100, null=True)),
                ('link', models.TextField()),
            ],
            bases=('fsm.widget',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.widget')),
                ('name', models.CharField(max_length=100, null=True)),
                ('link', models.TextField()),
            ],
            bases=('fsm.widget',),
        ),
        migrations.RemoveField(
            model_name='game',
            name='answer',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
