# Generated by Django 3.1 on 2020-08-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0003_auto_20200830_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamhistory',
            name='edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fsm.fsmedge'),
        ),
    ]
