# Generated by Django 3.0.8 on 2020-08-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0003_auto_20200821_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='fsm.ProblemMultiChoice'),
        ),
    ]
