# Generated by Django 3.1 on 2021-08-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0003_auto_20210817_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfileanswer',
            name='file_name',
        ),
    ]
