# Generated by Django 3.0.8 on 2020-12-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0003_auto_20201205_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsmstate',
            name='fsm',
        ),
        migrations.CreateModel(
            name='MainState',
            fields=[
                ('fsmstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.FSMState')),
                ('fsm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='fsm.FSM')),
            ],
            bases=('fsm.fsmstate',),
        ),
        migrations.CreateModel(
            name='HelpState',
            fields=[
                ('fsmstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.FSMState')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_states', to='fsm.FSMState')),
            ],
            bases=('fsm.fsmstate',),
        ),
    ]
