# Generated by Django 3.0.8 on 2021-03-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0003_event_maximum_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_team_cost',
            field=models.IntegerField(default=0),
        ),
    ]
