# Generated by Django 3.0.8 on 2020-12-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0004_auto_20201207_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsm',
            name='first_state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_fsm', to='fsm.MainState'),
        ),
        migrations.AlterField(
            model_name='fsmedge',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_edges', to='fsm.MainState'),
        ),
        migrations.AlterField(
            model_name='fsmedge',
            name='tail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_edges', to='fsm.MainState'),
        ),
        migrations.AlterField(
            model_name='helpstate',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_states', to='fsm.MainState'),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_histories', to='fsm.MainState'),
        ),
        migrations.AlterField(
            model_name='playerworkshop',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_workshop', to='fsm.MainState'),
        ),
    ]
