# Generated by Django 3.0.8 on 2020-09-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0004_fsm_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsm',
            name='active',
        ),
    ]
