# Generated by Django 3.0.8 on 2020-08-27 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0004_auto_20200827_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsmpage',
            name='state',
        ),
        migrations.AddField(
            model_name='fsmstate',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='fsm.FSMPage'),
        ),
    ]
