# Generated by Django 3.0.8 on 2020-11-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0004_auto_20201111_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedanswer',
            name='team_history',
        ),
        migrations.AddField(
            model_name='uploadfileanswer',
            name='file_name',
            field=models.CharField(default='dafualt_name.pdf', max_length=50),
            preserve_default=False,
        ),
    ]
