# Generated by Django 3.0.8 on 2021-03-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0004_event_event_team_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='lock',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fsmedge',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fsmedge',
            name='is_back_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fsmedge',
            name='min_score',
            field=models.FloatField(default=0.0),
        ),
    ]
