# Generated by Django 3.0.8 on 2020-11-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201113_1915'),
        ('fsm', '0005_auto_20201112_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('edge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fsm.FSMEdge')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='accounts.Player')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_histories', to='fsm.FSMState')),
            ],
        ),
        migrations.RemoveField(
            model_name='ability',
            name='team_history',
        ),
        migrations.DeleteModel(
            name='TeamHistory',
        ),
        migrations.AddField(
            model_name='ability',
            name='player_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='fsm.PlayerHistory'),
        ),
    ]
