# Generated by Django 3.0.8 on 2020-12-14 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0005_auto_20201207_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('fsmstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.FSMState')),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_page', models.ImageField(blank=True, null=True, upload_to='workshop/')),
                ('active', models.BooleanField(default=False)),
            ],
            bases=('fsm.fsmstate',),
        ),
    ]
