# Generated by Django 3.0.8 on 2020-09-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0005_remove_fsm_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_histories', to='fsm.FSMState'),
        ),
    ]
