# Generated by Django 3.1 on 2020-08-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200829_0928'),
        ('fsm', '0005_auto_20200827_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='accounts.participant')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='accounts.team')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submited_answers', to='accounts.participant')),
                ('team_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='fsm.teamhistory')),
            ],
        ),
        migrations.AddField(
            model_name='ability',
            name='team_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='fsm.teamhistory'),
        ),
        migrations.AddField(
            model_name='biganswer',
            name='submited_answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biganswer', to='fsm.submitedanswer'),
        ),
        migrations.AddField(
            model_name='multichoiceanswer',
            name='submited_answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multichoiceanswer', to='fsm.submitedanswer'),
        ),
        migrations.AddField(
            model_name='smallanswer',
            name='submited_answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smallanswer', to='fsm.submitedanswer'),
        ),
    ]
