# Generated by Django 3.0.8 on 2021-03-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0005_auto_20210324_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerhistory',
            name='edge',
        ),
        migrations.RemoveField(
            model_name='playerhistory',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='playerhistory',
            name='player',
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='inward_edge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fsm.FSMEdge'),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='player_workshop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='fsm.PlayerWorkshop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_histories', to='fsm.MainState'),
        ),
    ]
