# Generated by Django 3.0.8 on 2021-03-27 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_payment_discount_code'),
        ('fsm', '0006_auto_20210326_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='max_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submittedanswer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='accounts.Player'),
        ),
        migrations.AlterField(
            model_name='submittedanswer',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='fsm.Problem'),
        ),
    ]
