# Generated by Django 3.0.8 on 2020-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0006_auto_20201113_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerworkshop',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
