# Generated by Django 3.0.8 on 2020-10-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0007_fsmstate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsmstate',
            name='type',
        ),
    ]
