# Generated by Django 3.0.8 on 2020-09-11 12:45

from django.db import migrations, models
import fsm.models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0007_fsmstate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsmstate',
            name='type',
            field=models.CharField(choices=[('withMentor', 'withMentor'), ('withoutMentor', 'withoutMentor')], default=fsm.models.StateType['withMentor'], max_length=40),
        ),
    ]
