# Generated by Django 3.0.8 on 2020-10-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0008_remove_fsmstate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemUploadFileAnswer',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.Problem')),
            ],
            bases=('fsm.problem',),
        ),
        migrations.CreateModel(
            name='UploadFileAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.Answer')),
                ('answer_file', models.FileField(blank=True, max_length=4000, upload_to='AnswerFile')),
                ('problem', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='fsm.ProblemUploadFileAnswer')),
            ],
            bases=('fsm.answer',),
        ),
    ]
