# Generated by Django 3.0.8 on 2021-03-27 05:10

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0008_fsmedge_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
