# Generated by Django 3.0.8 on 2020-11-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0009_problemuploadfileanswer_uploadfileanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsmstate',
            name='page',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='page',
        ),
        migrations.AddField(
            model_name='fsm',
            name='first_state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_fsm', to='fsm.FSMState'),
        ),
        migrations.AddField(
            model_name='fsm',
            name='fsm_learning_type',
            field=models.CharField(choices=[('withMentor', 'Withmentor'), ('noMentor', 'Nomentor')], default='noMentor', max_length=40),
        ),
        migrations.AddField(
            model_name='fsm',
            name='fsm_p_type',
            field=models.CharField(choices=[('team', 'Team'), ('individual', 'Individual'), ('hybrid', 'Hybrid')], default='hybrid', max_length=40),
        ),
        migrations.AddField(
            model_name='widget',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget', to='fsm.FSMState'),
        ),
        migrations.AlterField(
            model_name='uploadfileanswer',
            name='answer_file',
            field=models.FileField(max_length=4000, upload_to='AnswerFile'),
        ),
        migrations.DeleteModel(
            name='FSMPage',
        ),
    ]
