# Generated by Django 3.1 on 2021-08-28 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsm', '0009_auto_20210820_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='fsms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fsm',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fsms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('RegistrationForm', 'Registrationform'), ('State', 'State'), ('Article', 'Article')], max_length=25),
        ),
    ]
