# Generated by Django 3.1 on 2021-08-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0011_auto_20210829_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsm',
            name='first_state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_fsm', to='fsm.state'),
        ),
        migrations.AlterField(
            model_name='fsmedge',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_edges', to='fsm.state'),
        ),
        migrations.AlterField(
            model_name='fsmedge',
            name='tail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_edges', to='fsm.state'),
        ),
        migrations.AlterField(
            model_name='helpstate',
            name='statee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_statess', to='fsm.state'),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_histories', to='fsm.state'),
        ),
        migrations.AlterField(
            model_name='playerworkshop',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_workshop', to='fsm.state'),
        ),
    ]
