# Generated by Django 3.1 on 2021-08-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0012_auto_20210829_0016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainState',
        ),
    ]
