# Generated by Django 3.1 on 2021-08-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0017_auto_20210829_0548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('tail', 'head')},
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
    ]
