# Generated by Django 3.1 on 2021-08-29 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0019_auto_20210829_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerhistory',
            name='player_workshop',
        ),
        migrations.AddField(
            model_name='player',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='fsm.state'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='fsm.player'),
            preserve_default=False,
        ),
    ]
