# Generated by Django 3.1 on 2021-08-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0021_auto_20210829_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
