# Generated by Django 3.1 on 2021-08-29 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0022_auto_20210829_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fsm.registrationreceipt'),
            preserve_default=False,
        ),
    ]
