# Generated by Django 3.1 on 2021-08-30 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0025_teamlock_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerhistory',
            name='inward_edge',
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='entered_by_edge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='fsm.edge'),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='reverse_enter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teamlock',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
