# Generated by Django 3.1 on 2021-08-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0027_auto_20210830_0537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamLock',
        ),
    ]
