# Generated by Django 3.1 on 2021-08-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0028_delete_teamlock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='is_hidden',
            new_name='is_visible',
        ),
    ]
