# Generated by Django 3.1 on 2021-10-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0029_auto_20210830_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accessible_after_closure',
            field=models.BooleanField(default=False),
        ),
    ]
