# Generated by Django 3.1 on 2021-10-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0038_auto_20211028_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='has_certificate',
            field=models.BooleanField(default=True),
        ),
    ]
