# Generated by Django 3.1 on 2021-11-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0041_auto_20211116_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
