# Generated by Django 3.1 on 2021-12-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0044_registrationform_audience_check_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationform',
            old_name='audience_check_status',
            new_name='audience_type',
        ),
    ]
