# Generated by Django 3.1 on 2022-01-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0048_auto_20211230_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='has_accepted',
        ),
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Waiting', max_length=15),
        ),
    ]
