# Generated by Django 3.1 on 2022-02-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0049_auto_20220119_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='crispWebsiteId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
