# Generated by Django 3.1 on 2022-08-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0055_auto_20220731_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='chat_room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
