# Generated by Django 3.1 on 2022-09-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0058_auto_20220925_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='is_spoilbox',
        ),
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='events-files/'),
        ),
    ]
