# Generated by Django 4.1.3 on 2023-01-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0060_alter_answer_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_solution',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='help_text',
            new_name='solution',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='max_corrections',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='max_score',
        ),
        migrations.AlterField(
            model_name='problem',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('Game', 'Game'), ('Video', 'Video'), ('Image', 'Image'), ('Aparat', 'Aparat'), ('Description', 'Description'), ('SmallAnswerProblem', 'Smallanswerproblem'), ('BigAnswerProblem', 'Biganswerproblem'), ('MultiChoiceProblem', 'Multichoiceproblem'), ('UploadFileProblem', 'Uploadfileproblem'), ('InviteeUsernameQuestion', 'Inviteeusernamequestion')], max_length=30),
        ),
    ]
