# Generated by Django 4.1.3 on 2023-01-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0060_alter_answer_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_solution',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='help_text',
            new_name='solution',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='max_corrections',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='max_score',
        ),
    ]
