# Generated by Django 4.1.3 on 2023-03-12 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0062_alter_widget_widget_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetHint',
            fields=[
                ('paper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.paper')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='fsm.widget')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.paper',),
        ),
    ]
