# Generated by Django 4.1.7 on 2023-04-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0065_audio_alter_widget_widget_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmittedAnswer',
        ),
    ]
