# Generated by Django 4.1.7 on 2023-06-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0067_newstate_fsm_course'),
        ('my_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='new_registration_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fsm', to='my_form.registrationform'),
        ),
        migrations.AddField(
            model_name='player',
            name='new_receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='my_form.registrationreceipt'),
        ),
        migrations.AddField(
            model_name='newstate',
            name='fsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nnew_states', to='fsm.fsm'),
        ),
        migrations.AddField(
            model_name='edge',
            name='new_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inward_edges', to='fsm.newstate'),
        ),
        migrations.AddField(
            model_name='edge',
            name='new_tail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_edges', to='fsm.newstate'),
        ),
        migrations.AddField(
            model_name='fsm',
            name='new_first_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_fsm', to='fsm.newstate'),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='new_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_histories', to='fsm.newstate'),
        ),
    ]
