# Generated by Django 4.1.3 on 2023-09-14 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0071_newfsm_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.answersheet'),
        ),
        migrations.AlterField(
            model_name='biganswer',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.biganswerproblem'),
        ),
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.multichoiceproblem'),
        ),
        migrations.AlterField(
            model_name='smallanswer',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.smallanswerproblem'),
        ),
        migrations.AlterField(
            model_name='uploadfileanswer',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.uploadfileproblem'),
        ),
    ]
