# Generated by Django 4.1.3 on 2023-09-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0072_alter_answer_answer_sheet_alter_biganswer_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
