# Generated by Django 3.1 on 2022-04-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0051_remove_event_crispwebsiteid'),
        ('scoring', '0002_auto_20220413_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='fsm.answer'),
        ),
    ]
