# Generated by Django 4.1.3 on 2023-02-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_alter_comment_answer_alter_score_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='answer',
            new_name='deliverable',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='answer',
            new_name='deliverable',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('deliverable', 'type')},
        ),
    ]
