# Generated by Django 4.1.3 on 2024-01-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_remove_scorepackage_scorable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deliverable',
        ),
        migrations.RemoveField(
            model_name='score',
            name='deliverable',
        ),
        migrations.DeleteModel(
            name='Deliverable',
        ),
    ]
