# Generated by Django 4.1.3 on 2024-01-02 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0088_remove_paper_criteria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_alter_user_phone_number'),
        ('scoring', '0011_remove_comment_deliverable_remove_score_deliverable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='basecondition_ptr',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='score_type',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='basecondition_ptr',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='score',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='scoretype',
            name='papers',
        ),
        migrations.AddField(
            model_name='scoretype',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_types', to='accounts.educationalinstitute'),
        ),
        migrations.AddField(
            model_name='scoretype',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoretype',
            name='programs',
            field=models.ManyToManyField(blank=True, null=True, related_name='score_types', to='fsm.event'),
        ),
        migrations.DeleteModel(
            name='BaseCondition',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
