# Generated by Django 4.1.3 on 2024-01-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0013_alter_scoretype_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='score_types_icons/'),
        ),
        migrations.AlterField(
            model_name='scoretype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.JSONField(default={}),
        ),
    ]
