# Generated by Django 3.1 on 2021-08-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210816_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinstitute',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
