# Generated by Django 3.1 on 2021-08-17 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210817_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinstitute',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
