# Generated by Django 3.1 on 2021-08-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0006_team_teammembership'),
        ('accounts', '0004_auto_20210817_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teamm',
        ),
    ]
