# Generated by Django 3.1 on 2021-08-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210821_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='remaining',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='accounts.merchandise'),
        ),
    ]
