# Generated by Django 4.1.7 on 2023-06-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('my_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registration_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='my_form.registrationform'),
        ),
    ]
