# Generated by Django 4.1.7 on 2023-06-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_registration_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='course',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='course',
            name='merchandise',
        ),
        migrations.RemoveField(
            model_name='course',
            name='registration_form',
        ),
    ]
