# Generated by Django 4.1.7 on 2023-08-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(upload_to='courses/'),
        ),
    ]
