# Generated by Django 4.1.3 on 2024-01-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('content_widget', '0001_initial'), ('content_widget', '0002_rename_description_textwidget'), ('content_widget', '0003_remove_image_content_ptr_delete_aparat_delete_image'), ('content_widget', '0004_remove_game_content_ptr_and_more'), ('content_widget', '0005_delete_content')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
