# Generated by Django 4.1.3 on 2023-12-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_widget', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Description',
            new_name='TextWidget',
        ),
    ]
