# Generated by Django 4.1.3 on 2024-01-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_widget', '0002_rename_description_textwidget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='content',
            name='widget_ptr',
        ),
        migrations.RemoveField(
            model_name='game',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='image',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='textwidget',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content_ptr',
        ),
        migrations.DeleteModel(
            name='Aparat',
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='TextWidget',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
