# Generated by Django 4.1.3 on 2024-01-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_widget', '0003_remove_image_content_ptr_delete_aparat_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='textwidget',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content_ptr',
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='TextWidget',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
