# Generated by Django 4.1.3 on 2024-01-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_widget', '0004_remove_game_content_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
