# Generated by Django 3.1 on 2021-08-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0006_team_teammembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='gender_partition_status',
            field=models.CharField(choices=[('OnlyMale', 'Onlymale'), ('OnlyFemale', 'Onlyfemale'), ('BothPartitioned', 'Bothpartitioned'), ('BothNonPartitioned', 'Bothnonpartitioned')], default='BothPartitioned', max_length=25),
        ),
    ]
