# Generated by Django 3.1 on 2021-08-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0010_auto_20210828_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsm',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='helpstate',
            name='state',
        ),
        migrations.AddField(
            model_name='helpstate',
            name='statee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='help_statess', to='fsm.mainstate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainstate',
            name='fsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statess', to='fsm.fsm'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('RegistrationForm', 'Registrationform'), ('State', 'State'), ('Hint', 'Hint'), ('Article', 'Article')], max_length=25),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('paper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.paper')),
                ('name', models.TextField(blank=True, null=True)),
                ('fsm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='fsm.fsm')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.paper',),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('paper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.paper')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_states', to='fsm.state')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.paper',),
        ),
    ]
