# Generated by Django 3.1 on 2021-08-28 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0014_auto_20210829_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsm',
            name='first_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_fsm', to='fsm.state'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='fsm.state'),
        ),
    ]
