# Generated by Django 3.1 on 2021-08-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0015_auto_20210829_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_back_enabled', models.BooleanField(default=True)),
                ('min_score', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('priority', models.IntegerField()),
                ('lock', models.CharField(blank=True, max_length=10, null=True)),
                ('has_lock', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_edges', to='fsm.state')),
                ('tail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_edges', to='fsm.state')),
            ],
        ),
        migrations.AlterField(
            model_name='ability',
            name='edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='fsm.edge'),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='inward_edge',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fsm.edge'),
        ),
        migrations.DeleteModel(
            name='FSMEdge',
        ),
    ]
