# Generated by Django 3.1 on 2021-08-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0016_auto_20210829_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
