# Generated by Django 3.1 on 2021-08-29 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsm', '0018_auto_20210829_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer_sheet_type',
            field=models.CharField(choices=[('RegistrationReceipt', 'Registrationreceipt'), ('StateAnswerSheet', 'Stateanswersheet')], max_length=25),
        ),
        migrations.AlterField(
            model_name='fsm',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fsms', to='fsm.event'),
        ),
        migrations.CreateModel(
            name='StateAnswerSheet',
            fields=[
                ('answersheet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.answersheet')),
                ('answer_sheet_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='fsm.state')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='fsm.player')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.answersheet',),
        ),
        migrations.AddField(
            model_name='player',
            name='fsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fsm.fsm'),
        ),
        migrations.AddField(
            model_name='player',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fsm.registrationreceipt'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
