# Generated by Django 3.1 on 2021-08-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0024_teamlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlock',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
    ]
