# Generated by Django 3.1 on 2021-08-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0026_auto_20210830_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='fsm.paper'),
        ),
    ]
