# Generated by Django 3.1 on 2021-10-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0032_auto_20211027_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatetemplate',
            old_name='template',
            new_name='template_file',
        ),
    ]
