# Generated by Django 3.1 on 2021-10-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0033_auto_20211027_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_file', models.FileField(upload_to='fonts/')),
            ],
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='font',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='fsm.font'),
        ),
    ]
