# Generated by Django 3.1 on 2021-10-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0034_auto_20211028_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='font_size',
            field=models.IntegerField(default=100),
        ),
    ]
