# Generated by Django 3.1 on 2021-10-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0035_certificatetemplate_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='font',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='fsm.font'),
        ),
    ]
