# Generated by Django 3.1 on 2021-10-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0037_auto_20211028_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='certificates_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
