# Generated by Django 3.1 on 2021-11-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0039_auto_20211028_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='deadline',
        ),
        migrations.AddField(
            model_name='paper',
            name='since',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='till',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='max_corrections',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StateAnswerSheet',
        ),
    ]
