# Generated by Django 3.1 on 2021-11-27 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsm', '0042_auto_20211116_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
