# Generated by Django 3.1 on 2022-05-02 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_basecondition_condition_criteria'),
        ('fsm', '0051_remove_event_crispwebsiteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='criteria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='scoring.criteria'),
        ),
    ]
