# Generated by Django 3.1 on 2022-05-06 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_basecondition_condition_criteria'),
        ('fsm', '0052_paper_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='criteria',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='scoring.criteria'),
        ),
    ]
