# Generated by Django 3.1 on 2022-09-25 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0057_auto_20220818_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='widget',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='fsm.paper'),
        ),
    ]
