# Generated by Django 4.1.3 on 2023-02-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0061_rename_is_solution_answer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('Game', 'Game'), ('Video', 'Video'), ('Image', 'Image'), ('Aparat', 'Aparat'), ('Description', 'Description'), ('SmallAnswerProblem', 'Smallanswerproblem'), ('BigAnswerProblem', 'Biganswerproblem'), ('MultiChoiceProblem', 'Multichoiceproblem'), ('UploadFileProblem', 'Uploadfileproblem'), ('Scorable', 'Scorable')], max_length=30),
        ),
    ]
