# Generated by Django 4.1.3 on 2023-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0063_widgethint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('RegistrationForm', 'Registrationform'), ('State', 'State'), ('Hint', 'Hint'), ('WidgetHint', 'Widgethint'), ('Article', 'Article')], max_length=25),
        ),
    ]
