# Generated by Django 4.1.7 on 2023-06-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('course', '0001_initial'),
        # ('base', '0003_alter_paper_creation_date_alter_paper_update_date_and_more'),
        ('fsm', '0066_delete_submittedanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEWState',
            fields=[
                ('paper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.paper')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('base.paper',),
        ),
        migrations.AddField(
            model_name='fsm',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fsms', to='course.course'),
        ),
    ]
