# Generated by Django 4.1.3 on 2024-01-05 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('fsm', '0067_newstate_fsm_course'), ('fsm', '0068_edge_new_head_edge_new_tail_fsm_new_first_state'), ('fsm', '0069_fsm_new_registration_form_newstate_fsm_and_more'), ('fsm', '0070_remove_fsm_course_remove_fsm_new_first_state_and_more'), ('fsm', '0071_newfsm_course'), ('fsm', '0072_alter_answer_answer_sheet_alter_biganswer_problem_and_more'), ('fsm', '0073_event_is_private'), ('fsm', '0074_rename_name_x_certificatetemplate_name_x_percentage_and_more'), ('fsm', '0075_alter_certificatetemplate_name_x_percentage_and_more'), ('fsm', '0076_article_is_private'), ('fsm', '0077_fsm_order_in_program'), ('fsm', '0078_choice_is_correct_alter_choice_problem_and_more'), ('fsm', '0079_remove_multichoiceanswer_choices'), ('fsm', '0080_delete_choiceselection'), ('fsm', '0081_multichoiceanswer_choices'), ('fsm', '0082_rename_description_textwidget_and_more'), ('fsm', '0083_alter_widget_widget_type_detailboxwidget'), ('fsm', '0084_rename_detail_detailboxwidget_details'), ('fsm', '0085_alter_detailboxwidget_details_alter_paper_paper_type'), ('fsm', '0086_event_faqs_paper_id_event_site_help_paper_id'), ('fsm', '0087_remove_newstate_fsm_remove_newstate_paper_ptr_and_more')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fsm', '0066_delete_submittedanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_alter_educationalinstitute_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.answersheet'),
        ),
        migrations.AlterField(
            model_name='biganswer',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.biganswerproblem'),
        ),
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.multichoiceproblem'),
        ),
        migrations.AlterField(
            model_name='smallanswer',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.smallanswerproblem'),
        ),
        migrations.AlterField(
            model_name='uploadfileanswer',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.uploadfileproblem'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='certificatetemplate',
            old_name='name_X',
            new_name='name_X_percentage',
        ),
        migrations.RenameField(
            model_name='certificatetemplate',
            old_name='name_Y',
            new_name='name_Y_percentage',
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name_X_percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name_Y_percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fsm',
            name='order_in_program',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='fsm.multichoiceproblem'),
        ),
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.multichoiceproblem'),
        ),
        migrations.RemoveField(
            model_name='multichoiceanswer',
            name='choices',
        ),
        migrations.DeleteModel(
            name='ChoiceSelection',
        ),
        migrations.AddField(
            model_name='multichoiceanswer',
            name='choices',
            field=models.ManyToManyField(to='fsm.choice'),
        ),
        migrations.RenameModel(
            old_name='Description',
            new_name='TextWidget',
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('Game', 'Game'), ('Video', 'Video'), ('Image', 'Image'), ('Aparat', 'Aparat'), ('Audio', 'Audio'), ('TextWidget', 'Textwidget'), ('SmallAnswerProblem', 'Smallanswerproblem'), ('BigAnswerProblem', 'Biganswerproblem'), ('MultiChoiceProblem', 'Multichoiceproblem'), ('UploadFileProblem', 'Uploadfileproblem'), ('Scorable', 'Scorable')], max_length=30),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('Game', 'Game'), ('Video', 'Video'), ('Image', 'Image'), ('Aparat', 'Aparat'), ('Audio', 'Audio'), ('TextWidget', 'Textwidget'), ('DetailBoxWidget', 'Detailboxwidget'), ('SmallAnswerProblem', 'Smallanswerproblem'), ('BigAnswerProblem', 'Biganswerproblem'), ('MultiChoiceProblem', 'Multichoiceproblem'), ('UploadFileProblem', 'Uploadfileproblem'), ('Scorable', 'Scorable')], max_length=30),
        ),
        migrations.CreateModel(
            name='DetailBoxWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.widget')),
                ('title', models.TextField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsm.paper')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.widget',),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('RegistrationForm', 'Registrationform'), ('State', 'State'), ('Hint', 'Hint'), ('WidgetHint', 'Widgethint'), ('Article', 'Article'), ('General', 'General')], max_length=25),
        ),
        migrations.AddField(
            model_name='event',
            name='FAQs_paper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='site_help_paper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
