# Generated by Django 4.1.3 on 2023-06-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0067_newstate_fsm_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='new_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inward_edges', to='fsm.newstate'),
        ),
        migrations.AddField(
            model_name='edge',
            name='new_tail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_edges', to='fsm.newstate'),
        ),
        migrations.AddField(
            model_name='fsm',
            name='new_first_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_fsm', to='fsm.newstate'),
        ),
    ]
