# Generated by Django 4.1.3 on 2023-06-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0068_edge_new_head_edge_new_tail_fsm_new_first_state'),
        # ('my_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='new_registration_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fsm', to='my_form.registrationform'),
        ),
        migrations.AddField(
            model_name='newstate',
            name='fsm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nnew_states', to='fsm.fsm'),
        ),
        migrations.AddField(
            model_name='player',
            name='new_receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='my_form.registrationreceipt'),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='new_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_histories', to='fsm.newstate'),
        ),
    ]
