# Generated by Django 4.1.7 on 2023-06-20 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        # ('my_form', '0001_initial'),
        ('accounts', '0014_alter_educationalinstitute_polymorphic_ctype_and_more'),
        ('fsm', '0069_fsm_new_registration_form_newstate_fsm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsm',
            name='course',
        ),
        migrations.RemoveField(
            model_name='fsm',
            name='new_first_state',
        ),
        migrations.RemoveField(
            model_name='fsm',
            name='new_registration_form',
        ),
        migrations.CreateModel(
            name='NEWFSM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='workshop/')),
                ('is_active', models.BooleanField(default=True)),
                ('fsm_learning_type', models.CharField(choices=[('Supervised', 'Supervised'), ('Unsupervised', 'Unsupervised')], default='Unsupervised', max_length=40)),
                ('fsm_p_type', models.CharField(choices=[('Team', 'Team'), ('Individual', 'Individual'), ('Hybrid', 'Hybrid')], default='Individual', max_length=40)),
                ('lock', models.CharField(blank=True, max_length=10, null=True)),
                ('team_size', models.IntegerField(default=3)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('first_state', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_fsm', to='fsm.newstate')),
                ('mentors', models.ManyToManyField(blank=True, related_name='new_fsms', to=settings.AUTH_USER_MODEL)),
                ('merchandise', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_fsm', to='accounts.merchandise')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_fsms', to='accounts.educationalinstitute')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                # ('registration_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fsm', to='my_form.registrationform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
