# Generated by Django 4.1.7 on 2023-06-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('course', '0005_initial'),
        ('fsm', '0070_remove_fsm_course_remove_fsm_new_first_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfsm',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fsms', to='course.course'),
        ),
    ]
