# Generated by Django 4.1.3 on 2023-10-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0073_event_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatetemplate',
            old_name='name_X',
            new_name='name_X_percentage',
        ),
        migrations.RenameField(
            model_name='certificatetemplate',
            old_name='name_Y',
            new_name='name_Y_percentage',
        ),
    ]
