# Generated by Django 4.1.3 on 2023-10-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0074_rename_name_x_certificatetemplate_name_x_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name_X_percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name_Y_percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
