# Generated by Django 4.1.3 on 2023-11-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0077_fsm_order_in_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='fsm.multichoiceproblem'),
        ),
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fsm.multichoiceproblem'),
        ),
    ]
