# Generated by Django 4.1.3 on 2023-11-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0078_choice_is_correct_alter_choice_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multichoiceanswer',
            name='choices',
        ),
    ]
