# Generated by Django 4.1.3 on 2023-11-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0079_remove_multichoiceanswer_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceSelection',
        ),
    ]
