# Generated by Django 4.1.3 on 2023-11-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0080_delete_choiceselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoiceanswer',
            name='choices',
            field=models.ManyToManyField(to='fsm.choice'),
        ),
    ]
