# Generated by Django 4.1.3 on 2023-12-18 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0082_rename_description_textwidget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('Game', 'Game'), ('Video', 'Video'), ('Image', 'Image'), ('Aparat', 'Aparat'), ('Audio', 'Audio'), ('TextWidget', 'Textwidget'), ('DetailBoxWidget', 'Detailboxwidget'), ('SmallAnswerProblem', 'Smallanswerproblem'), ('BigAnswerProblem', 'Biganswerproblem'), ('MultiChoiceProblem', 'Multichoiceproblem'), ('UploadFileProblem', 'Uploadfileproblem'), ('Scorable', 'Scorable')], max_length=30),
        ),
        migrations.CreateModel(
            name='DetailBoxWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.widget')),
                ('title', models.TextField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsm.paper')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.widget',),
        ),
    ]
