# Generated by Django 4.1.3 on 2023-12-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0083_alter_widget_widget_type_detailboxwidget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailboxwidget',
            old_name='detail',
            new_name='details',
        ),
    ]
