# Generated by Django 4.1.3 on 2023-12-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0085_alter_detailboxwidget_details_alter_paper_paper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='FAQs_paper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='site_help_paper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
