# Generated by Django 4.1.3 on 2024-01-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0086_event_faqs_paper_id_event_site_help_paper_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstate',
            name='fsm',
        ),
        migrations.RemoveField(
            model_name='newstate',
            name='paper_ptr',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='new_head',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='new_tail',
        ),
        migrations.RemoveField(
            model_name='player',
            name='new_receipt',
        ),
        migrations.RemoveField(
            model_name='playerhistory',
            name='new_state',
        ),
        migrations.DeleteModel(
            name='NEWFSM',
        ),
        migrations.DeleteModel(
            name='NEWState',
        ),
    ]
