# Generated by Django 4.1.3 on 2024-01-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0087_remove_newstate_fsm_remove_newstate_paper_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='criteria',
        ),
    ]
