# Generated by Django 4.1.3 on 2024-01-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0013_alter_scoretype_institute'),
        ('fsm', '0088_remove_paper_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoring.cost'),
        ),
        migrations.AddField(
            model_name='widget',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoring.reward'),
        ),
    ]
