# Generated by Django 4.1.3 on 2024-01-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0090_event_show_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='be_corrected',
            field=models.BooleanField(default=False),
        ),
    ]
