# Generated by Django 4.2.9 on 2024-02-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0093_rename_bale_id_programcontactinfo_bale_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='party',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='party',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fsm',
            name='party',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
