# Generated by Django 4.1.7 on 2023-06-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0070_remove_fsm_course_remove_fsm_new_first_state_and_more'),
        ('course', '0003_remove_course_creator_remove_course_holder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
