# Generated by Django 4.1.3 on 2023-10-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('ProgramsPage', 'Programs Page')], default='ProgramsPage', max_length=30)),
                ('image', models.ImageField(upload_to='websiteappearance/')),
                ('is_active', models.BooleanField(default=False)),
                ('redirect_to', models.URLField()),
            ],
        ),
    ]
