# Generated by Django 4.1.3 on 2023-10-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteappearance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='desktop_image',
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(default=None, upload_to='websiteappearance/'),
            preserve_default=False,
        ),
    ]
