# Generated by Django 3.0.8 on 2020-12-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_pay_type', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeBidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=50)),
                ('bid', models.IntegerField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='auction.OneTimeAuction')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneTimeBidders', to='accounts.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='onetimeauction',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.OneTimeBidder'),
        ),
    ]
