# Generated by Django 3.1 on 2020-08-29 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimeauction',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oneTimeAuction', to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='onetimebidder',
            name='value',
            field=models.IntegerField(default=50),
        ),
    ]
