# Generated by Django 3.1 on 2020-08-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20200829_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimeauction',
            name='team',
        ),
    ]
