# Generated by Django 3.0.4 on 2021-05-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0001_initial'),
        ('fsm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_players', to='fsm.Event'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.DiscountCode'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='accounts.Member'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='workshops',
            field=models.ManyToManyField(related_name='workshop_mentors', to='fsm.FSM'),
        ),
        migrations.AddField(
            model_name='eventowner',
            name='events',
            field=models.ManyToManyField(related_name='event_owners', to='fsm.Event'),
        ),
        migrations.AddField(
            model_name='eventowner',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.Member'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='payment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_payment', to='accounts.Participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='event_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_participants', to='accounts.Team'),
        ),
        migrations.AddField(
            model_name='participant',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participant', to='accounts.Member'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_discount_code', to='accounts.Participant'),
        ),
    ]
