# Generated by Django 3.0.8 on 2020-08-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
