# Generated by Django 3.0.8 on 2020-11-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0002_auto_20201108_2256'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='workshops',
            field=models.ManyToManyField(related_name='players', through='fsm.PlayerWorkshop', to='fsm.FSM'),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
