# Generated by Django 3.0.8 on 2020-08-28 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('authority', models.CharField(max_length=37)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('REPETITIOUS', 'REPETITIOUS'), ('FAILED', 'FAILED')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uniq_code', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Participant')),
            ],
        ),
    ]
