# Generated by Django 3.0.8 on 2020-08-29 08:12

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    participant = apps.get_model('accounts', 'Participant')
    for row in participant.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ), migrations.RunPython(gen_uuid),
    ]
