# Generated by Django 3.0.8 on 2020-11-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201108_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='grade',
            field=models.CharField(blank=True, choices=[('پیش\u200c از دبستان', 'Pre'), ('اول', 'One'), ('دوم', 'Two'), ('سوم', 'Three'), ('چهارم', 'Four'), ('پنچم', 'Five'), ('ششم', 'Six'), ('هفتم', 'Seven'), ('هشتم', 'Eight'), ('نهم', 'Nine'), ('دهم', 'Ten'), ('یازدهم', 'Eleven'), ('دوازدهم', 'Twelve')], max_length=15, null=True),
        ),
    ]
