# Generated by Django 3.0.8 on 2020-08-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200823_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='grade',
            field=models.CharField(choices=[('ten', 'Ten'), ('eleven', 'Eleven'), ('twelve', 'Twelve')], max_length=10),
        ),
    ]
