# Generated by Django 3.0.8 on 2021-03-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210307_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='selection_doc',
            field=models.FileField(blank=True, null=True, upload_to='selection_answers/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_participants', to='accounts.Team'),
        ),
    ]
