# Generated by Django 3.0.8 on 2020-08-29 10:36

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    team = apps.get_model('accounts', 'Team')
    for row in team.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_participant_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ), migrations.RunPython(gen_uuid)
    ]
