# Generated by Django 3.0.8 on 2020-11-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(related_name='team_set', to='accounts.Participant'),
        ),
    ]
