# Generated by Django 3.0.8 on 2020-08-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200823_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
