# Generated by Django 3.1 on 2020-08-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0001_initial'),
        ('accounts', '0004_auto_20200829_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='fsm.fsmstate'),
        ),
    ]
