# Generated by Django 3.0.8 on 2021-03-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210307_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_participated',
        ),
        migrations.AddField(
            model_name='participant',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_participated',
            field=models.BooleanField(default=False),
        ),
    ]
