# Generated by Django 3.0.8 on 2021-03-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210308_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
