# Generated by Django 3.0.8 on 2020-08-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200829_1509'),
        ('accounts', '0004_auto_20200829_0928'),
    ]

    operations = [
    ]
