# Generated by Django 3.0.8 on 2020-11-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_player_player_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(choices=[('TEAM', 'Team'), ('PARTICIPANT', 'Participant')], max_length=15),
        ),
    ]
