# Generated by Django 3.0.8 on 2020-11-13 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201110_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='uuid',
        ),
        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
