# Generated by Django 3.1 on 2021-10-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210821_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinstitute',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationalinstitute',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
