# Generated by Django 3.0.8 on 2020-08-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_team_current_state'),
        ('accounts', '0007_auto_20200829_1822'),
    ]

    operations = [
    ]
