# Generated by Django 3.0.8 on 2020-08-30 14:07

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    participant = apps.get_model('accounts', 'Participant')
    for row in participant.objects.all():
        row.member.uuid = row.uuid
        row.member.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20200830_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ), migrations.RunPython(gen_uuid)
    ]
