# Generated by Django 3.0.8 on 2021-03-16 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210316_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
