# Generated by Django 3.0.8 on 2020-08-30 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_member_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='member',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
