# Generated by Django 3.1 on 2022-01-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0049_auto_20220119_1626'),
        ('accounts', '0009_auto_20211124_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='member',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='workshops',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='event_team',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='member',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='player_ptr',
        ),
        migrations.RemoveField(
            model_name='teamm',
            name='player_ptr',
        ),
        migrations.DeleteModel(
            name='EventOwner',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Teamm',
        ),
    ]
