# Generated by Django 3.0.8 on 2021-03-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210316_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='participant',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('REPETITIOUS', 'REPETITIOUS'), ('FAILED', 'FAILED'), ('STARTED', 'STARTED')], max_length=100),
        ),
    ]
