# Generated by Django 3.1 on 2022-02-12 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220206_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
