# Generated by Django 3.0.8 on 2021-03-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210317_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_payment', to='accounts.Participant'),
        ),
    ]
