# Generated by Django 3.1 on 2022-02-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220212_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='discount_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='accounts.discountcode'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='voucher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='accounts.voucher'),
        ),
    ]
