# Generated by Django 3.0.8 on 2020-08-31 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0003_auto_20200901_0025'),
        ('accounts', '0012_auto_20200831_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='fsm.FSMState'),
        ),
    ]
