# Generated by Django 3.0.8 on 2021-03-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210317_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.DiscountCode'),
        ),
    ]
