# Generated by Django 3.0.8 on 2021-03-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_payment_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
