# Generated by Django 3.0.4 on 2021-05-24 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210524_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventowner',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.Member'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='accounts.Member'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participant', to='accounts.Member'),
        ),
    ]
