# Generated by Django 4.1.3 on 2023-02-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoring', '0007_deliverable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('scorable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoring.scorable')),
                ('text', models.TextField()),
                ('required', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('InviteeUsername', 'Inviteeusername')], max_length=30)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('scoring.scorable',),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('deliverable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoring.deliverable')),
                ('response_type', models.CharField(choices=[('InviteeUsernameResponse', 'Inviteeusernameresponse')], max_length=30)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('scoring.deliverable',),
        ),
        migrations.CreateModel(
            name='InviteeUsernameQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.question')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('question.question',),
        ),
        migrations.CreateModel(
            name='InviteeUsernameResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.response')),
                ('username', models.CharField(max_length=15)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question.inviteeusernamequestion')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('question.response',),
        ),
    ]
