# Generated by Django 4.1.3 on 2023-02-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0062_alter_widget_widget_type'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='answer_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='fsm.answersheet'),
        ),
    ]
