# Generated by Django 4.1.3 on 2023-02-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('InviteeUsername', 'Inviteeusername')], default='InviteeUsername', max_length=30),
            preserve_default=False,
        ),
    ]
