# Generated by Django 4.1.7 on 2023-06-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('question', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_sheet',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AlterField(
            model_name='question',
            name='widget_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.widget'),
        ),
    ]
