# Generated by Django 4.1.7 on 2023-06-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='choice',
        #     name='problem',
        # ),
        # migrations.RemoveField(
        #     model_name='choiceselection',
        #     name='choice',
        # ),
        # migrations.RemoveField(
        #     model_name='choiceselection',
        #     name='multi_choice_answer',
        # ),
        # migrations.RemoveField(
        #     model_name='inviteeusernameanswer',
        #     name='answer_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='inviteeusernameanswer',
        #     name='question',
        # ),
        # migrations.RemoveField(
        #     model_name='inviteeusernamequestion',
        #     name='question_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='longanswer',
        #     name='answer_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='longanswer',
        #     name='problem',
        # ),
        # migrations.RemoveField(
        #     model_name='longanswerquestion',
        #     name='question_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='multichoiceanswer',
        #     name='answer_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='multichoiceanswer',
        #     name='choices',
        # ),
        # migrations.RemoveField(
        #     model_name='multichoiceanswer',
        #     name='problem',
        # ),
        # migrations.RemoveField(
        #     model_name='multichoicequestion',
        #     name='question_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='score',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='widget_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='shortanswer',
        #     name='answer_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='shortanswer',
        #     name='problem',
        # ),
        # migrations.RemoveField(
        #     model_name='shortanswerquestion',
        #     name='question_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='uploadfileanswer',
        #     name='answer_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='uploadfileanswer',
        #     name='problem',
        # ),
        # migrations.RemoveField(
        #     model_name='uploadfilequestion',
        #     name='question_ptr',
        # ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='ChoiceSelection',
        ),
        migrations.DeleteModel(
            name='InviteeUsernameAnswer',
        ),
        migrations.DeleteModel(
            name='InviteeUsernameQuestion',
        ),
        migrations.DeleteModel(
            name='LongAnswer',
        ),
        migrations.DeleteModel(
            name='LongAnswerQuestion',
        ),
        migrations.DeleteModel(
            name='MultiChoiceAnswer',
        ),
        migrations.DeleteModel(
            name='MultiChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='ShortAnswer',
        ),
        migrations.DeleteModel(
            name='ShortAnswerQuestion',
        ),
        migrations.DeleteModel(
            name='UploadFileAnswer',
        ),
        migrations.DeleteModel(
            name='UploadFileQuestion',
        ),
    ]
