# Generated by Django 4.1.3 on 2024-01-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_head_group_registration_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='head',
        ),
        migrations.RemoveField(
            model_name='group',
            name='registration_form',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invitee',
        ),
    ]
