# Generated by Django 4.1.3 on 2024-01-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_group_head_remove_group_registration_form_and_more'),
        ('my_form', '0002_alter_receipt_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
