# Generated by Django 4.1.3 on 2024-01-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_widget', '0002_remove_choiceselection_choice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
