# Generated by Django 4.1.3 on 2024-01-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_widget', '0003_delete_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiChoiceQuestion',
        ),
    ]
