# Generated by Django 4.1.3 on 2024-01-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_widget', '0006_delete_uploadfilequestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LongAnswerQuestion',
        ),
    ]
