# Generated by Django 3.0.8 on 2021-03-21 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fsm', '0004_event_event_team_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('player_workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsm.PlayerWorkshop')),
            ],
        ),
    ]
