# Generated by Django 3.0.4 on 2021-05-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fsm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('player_workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsm.PlayerWorkshop')),
                ('submitted_answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='fsm.SubmittedAnswer')),
            ],
        ),
    ]
