# Generated by Django 3.1 on 2021-08-29 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0023_auto_20210830_0320'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='scoretransaction',
            name='player_workshop',
        ),
        migrations.RemoveField(
            model_name='scoretransaction',
            name='submitted_answer',
        ),
        migrations.AddField(
            model_name='scoretransaction',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='fsm.answer'),
        ),
        migrations.AddField(
            model_name='scoretransaction',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fsm.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoretransaction',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='scoring.scoretype'),
        ),
    ]
