# Generated by Django 3.0.8 on 2021-03-26 20:09

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0006_auto_20210326_1215'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretransaction',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fsm.Answer'),
        ),
    ]
