# Generated by Django 3.0.8 on 2021-03-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_scoretransaction_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoretransaction',
            old_name='source',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='scoretransaction',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
