# Generated by Django 3.0.8 on 2021-03-27 01:19

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0007_auto_20210327_0549'),
        ('scoring', '0003_auto_20210327_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoretransaction',
            name='answer',
        ),
        migrations.AddField(
            model_name='scoretransaction',
            name='submitted_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='fsm.SubmittedAnswer'),
        ),
    ]
