# Generated by Django 4.1.3 on 2023-02-05 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0061_rename_is_solution_answer_is_correct_and_more'),
        ('scoring', '0005_alter_basecondition_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorable',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fsm.widget')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fsm.widget',),
        ),
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scoretype',
            options={},
        ),
        migrations.RenameField(
            model_name='score',
            old_name='score_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='scoretype',
            name='polymorphic_ctype',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('answer', 'type')},
        ),
        migrations.CreateModel(
            name='ScorePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('scorable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_packages', to='scoring.scorable')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_packages', to='scoring.scoretype')),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='polymorphic_ctype',
        ),
    ]
