# Generated by Django 4.1.3 on 2023-02-08 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_deliverable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.deliverable'),
        ),
        migrations.AlterField(
            model_name='score',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scoring.deliverable'),
        ),
    ]
