# Generated by Django 4.1.7 on 2023-06-19 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_educationalinstitute_polymorphic_ctype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoring', '0009_rename_answer_comment_deliverable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorepackage',
            name='scorable',
        ),
        migrations.RemoveField(
            model_name='scorepackage',
            name='type',
        ),
        migrations.AlterModelOptions(
            name='deliverable',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='deliverable',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='score',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='accounts.educationalinstitute'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='deliverable_type',
            field=models.CharField(choices=[('Answer', 'Answer'), ('Receipt', 'Receipt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scoring.deliverable', unique=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='Scorable',
        ),
        migrations.DeleteModel(
            name='ScorePackage',
        ),
        migrations.RemoveField(
            model_name='score',
            name='type',
        ),
    ]
