# Generated by Django 3.0.8 on 2020-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='isPushed',
            field=models.BooleanField(default=False),
        ),
    ]
