# Generated by Django 4.1.7 on 2023-06-19 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_paper_options_remove_paper_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='widget',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='widget',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
