# Generated by Django 3.1 on 2022-04-03 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import event_metadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fsm', '0051_remove_event_crispwebsiteid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=event_metadata.models.get_staff_info_upload_path)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_infos', to=settings.AUTH_USER_MODEL)),
                ('registration_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_infos', to='fsm.registrationform')),
                ('team', models.ManyToManyField(blank=True, to='event_metadata.StaffTeam')),
            ],
            options={
                'unique_together': {('account', 'registration_form')},
            },
        ),
    ]
