# Generated by Django 4.1.7 on 2023-06-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_metadata', '0002_auto_20220409_0631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffInfo',
        ),
        migrations.DeleteModel(
            name='StaffTeam',
        ),
    ]
